export const GETTERS = {
  IS_LOADING: "APP/IS_LOADING"
};

export const MUTATIONS = {
  UPDATE_LOADING: "APP/UPDATE_LOADING"
};

export const ACTIONS = {
  ADD_ERROR_NOTIFICATION: "APP/ADD_ERROR_NOTIFICATION"
};

export default {
  GETTERS,
  MUTATIONS
};
