export const GETTERS = {
  DATA: "ARTICLES/DATA",
  CURRENT_ARTICLE: "ARTICLES/CURRENT_ARTICLE"
};

export const MUTATIONS = {
  UPDATE: "ARTICLES/UPDATE",
  UPDATE_CURRENT: "ARTICLES/UPDATE_CURRENT"
};

export const ACTIONS = {
  GET_ALL: "ARTICLES/GET_ALL",
  ADD: "ARTICLES/ADD",
  UPDATE: "ARTICLES/UPDATE",
  GET_BY_ID: "ARTICLES/GET_BY_ID",
  REMOVE: "ARTICLES/REMOVE"
};

export default {
  GETTERS,
  MUTATIONS,
  ACTIONS
};
